version: 2.1

orbs:
  yarn: artsy/yarn@2.1.1
  hokusai: artsy/hokusai@0.7.0
  node: artsy/node@0.1.0
  horizon: artsy/release@0.0.1

jobs:
  acceptance:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - yarn/setup
      - run:
          name: Acceptance Tests
          command: yarn acceptance src/test/acceptance/*.js

  validate_production_schema:
    executor: node/build
    steps:
      - yarn/setup
      - run:
          name: Validate Production Schema
          command: node scripts/validateSchemas.js production

  build:
    executor: node/build
    steps:
      - yarn/setup
      - run:
          name: Build force assets
          command: yarn assets
      - store_artifacts:
          path: ~/project/.artifacts
      - run:
          name: Duplicates Report
          command: curl "https://artsy-dupe-report.now.sh/packages/dupe-report/now.js?owner=artsy&repo=force&buildNum=$CIRCLE_BUILD_NUM"

  danger:
    executor: node/build
    steps:
      - yarn/setup
      - run:
          name: Danger
          command: DANGER_GITHUB_API_TOKEN="15e52de81a772b174cc5""e1813d0083564c69c325" yarn danger ci

  test:
    executor: node/build
    parallelism: 2
    steps:
      - yarn/setup
      - run:
          name: Test
          command: COMMIT_HASH_FULL=$(git rev-parse HEAD) CODECOV_TOKEN=$CODECOV_TOKEN BRANCH_NAME=$CIRCLE_BRANCH yarn test
      - store_test_results:
          path: reports

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  default:
    jobs:
      - horizon/block:
          <<: *only_release
          context: horizon
          project_id: 11

      # Pre-staging
      - yarn/update-cache:
          <<: *not_staging_or_release
      - test:
          <<: *not_staging_or_release
      - acceptance:
          <<: *not_staging_or_release
      - build:
          <<: *not_staging_or_release
      - danger:
          <<: *not_staging_or_release

      # Staging
      - hokusai/push:
          name: push-staging-image
          <<: *only_master
          requires:
            - test
            - acceptance
            - build

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: force
          requires:
            - push-staging-image

      # Release
      - validate_production_schema:
          <<: *only_release
      - hokusai/deploy-production:
          <<: *only_release
          requires:
            - horizon/block
            - validate_production_schema
